# Use root/example as user/password credentials

services:
  data_catalog_service:
    image: data-catalog-service
    container_name: data-catalog-service
    environment:
      INTERNAL_CONTEXT_BROKER_URL: "http://orion:1026/ngsi-ld/v1"
      PUBLIC_CONTEXT_BROKER_URL: "http://api-gw:1026/ngsi-ld/v1"
      DOMAIN_ID: "CANDIL"
      ORGANIZATION_ID: "CANDIL"
      LOGLEVEL: "DEBUG"
      MONGO_DB_URI: "mongodb://mongo:27017"
    command: "dev --host 0.0.0.0 --port 80"
    ports:
      - 8000:80
    volumes:
      - ./data_catalog_service:/app/data_catalog_service
    depends_on:
      - orion
  mongo:
    image: mongo:7.0.12
    volumes:
        - mongo-orion-domain:/data/db
    ports:
      - "27017:27017"
    restart: always
  orion:
    image: registry.gitlab.aeros-project.eu/aeros-public/common-deployments/orion-ld:1.1.1
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -mongocOnly -brokerId domainA -forwarding -wip entityMaps,distSubs -t 70-99 -logLevel DEBUG -disableFileLog -noArrayReduction
    restart: always
volumes:
  mongo-orion-domain:
